###
###### Command to Run:  oc process -f deployable.yaml -p APP_NAME=myapp1 -p APP_PROJECT_NAME=default | oc apply -f -
###
apiVersion: v1
kind: Template
metadata:
  name: route-${APP_NAME}-template
objects:
  - apiVersion: app.ibm.com/v1alpha1
    kind: Deployable
    metadata:
      name: ${APP_NAME}-route-deployable
      namespace: ${APP_PROJECT_NAME}
      labels:
        app: ${APP_NAME}
        package: ${APP_NAME}-package
    spec:
      template:
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: ${APP_NAME}
          labels:
            app: ${APP_NAME}
        spec:
          port:
            targetPort: 3000
          to:
            kind: Service
            name: ${APP_NAME}
parameters:
  - name: APP_NAME
    required: true
    value: ""
  - name: APP_PROJECT_NAME
    required: true
    value: ""
