#### Command to run: oc process -f channel/deployable-configmap-template.yaml -p  APP_NAME=crm-microservice -p CHANNEL_PROJECT_NAME=torobank-hub | oc create -
apiVersion: v1
kind: Template
metadata:
  name: mcm-${APP_NAME}-configmap-template
objects:
  - apiVersion: app.ibm.com/v1alpha1
    kind: Deployable
    metadata:
      name: configmap-deployable
      namespace: ${CHANNEL_PROJECT_NAME}
      labels:
        package: ${APP_NAME}-package
    spec:
      template:
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: ${APP_NAME}
        data:
          # Configuration values can be set as key-value properties
          database: mongodb
          database_uri: mongodb://localhost:27017
parameters:
  - name: APP_NAME
    required: true
    value: ""
  - name: CHANNEL_PROJECT_NAME
    required: true
    value: ""
