###
###### Command to Run:  oc process -f deployable.yaml -p APP_NAME=myapp1 -p APP_PROJECT_NAME=default | oc apply -f -
###
apiVersion: v1
kind: Template
metadata:
  name: deploymentconfig-${APP_NAME}-template
objects:
  - apiVersion: app.ibm.com/v1alpha1
    kind: Deployable
    metadata:
      name: ${APP_NAME}-deployment-deployable
      namespace: ${APP_PROJECT_NAME}
      labels:
        app: ${APP_NAME}
        package: ${APP_NAME}-package
    spec:
      template:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        metadata:
          labels:
            app: ${APP_NAME}
          name: ${APP_NAME}-dc
        spec:
          replicas: 1
          selector:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-dc
          strategy:
            resources: {}
            strategy:
              type: Recreate
              recreateParams:
                timeoutSeconds: 600
          template:
            metadata:
              labels:
                app: ${APP_NAME}
                deploymentconfig: ${APP_NAME}-dc
            spec:
              containers:
                - image: alchen99/express-hello:latest
                  imagePullPolicy: Always
                  name: ${APP_NAME}
                  ports:
                    - containerPort: 3000
                      protocol: TCP
              securityContext: {}
              terminationGracePeriodSeconds: 30
        #   triggers:
        #     - type: ConfigChange
        #     - imageChangeParams:
        #         automatic: true
        #         containerNames:
        #           - ${APP_NAME}
        #         from:
        #           kind: ImageStreamTag
        #           name: ${APP_NAME}:latest
        #       type: ImageChange
parameters:
  - name: APP_NAME
    required: true
    value: ""
  - name: APP_PROJECT_NAME
    required: true
    value: ""
