#### Command to run: oc process -f subscription/application.yaml  \
## -p SUBSCRIPTION_NAME=crmportal-backend-resources -p SUBSCRIPTION_PROJECT_NAME=torobank-workload -p APPLICATION_NAME=crm-portal | oc apply -f -
apiVersion: v1
kind: Template
metadata:
  name: placementrule-${SUBSCRIPTION_NAME}-template
objects:
  - apiVersion: app.ibm.com/v1alpha1
    kind: PlacementRule
    metadata:
      name: ${SUBSCRIPTION_NAME}-placement
      namespace: ${SUBSCRIPTION_PROJECT_NAME}
      labels:
        app: ${SUBSCRIPTION_NAME}
    spec:
      clusterReplicas: 3
      clusterLabels:
        matchLabels:
          "${{CLUSTERS_LABELS}}"
          # allow-mcm: "yes"
          # environment: Dev
parameters:
  - name: SUBSCRIPTION_NAME
    required: true
    value: ""
  - name: SUBSCRIPTION_PROJECT_NAME
    required: true
    value: ""
  - name: CLUSTERS_LABELS
    required: true
    value: '{"environment": "Dev"}'
